import type { ControlTowerSnapshot } from "@/modules/control-tower/domain/control-tower.types";

export const mockControlTowerSnapshot: ControlTowerSnapshot = {
  dealershipName: "Reynolds Auto Group",
  regionLabel: "North Houston Recon Command",
  updatedAtLabel: "Updated 12 seconds ago",
  kpis: [
    {
      code: "open-units",
      label: "Open Vehicles",
      value: "130",
      delta: "+8 since 06:00",
      emphasis: "primary",
    },
    {
      code: "avg-cycle",
      label: "Active Cycle Time",
      value: "5.4 days",
      delta: "-0.6 vs last week",
      emphasis: "neutral",
    },
    {
      code: "breaches",
      label: "SLA Pressure",
      value: "17",
      delta: "4 critical lanes",
      emphasis: "warning",
    },
    {
      code: "close-today",
      label: "Closed Today",
      value: "23",
      delta: "82% of target",
      emphasis: "neutral",
    },
  ],
  stageGroups: [
    {
      code: "pre-recon",
      label: "Pre-Recon",
      totalVehicles: 181,
      avgCycleDays: 7.1,
      rows: [
        {
          code: "pre-recon-vehicles",
          label: "Pre-Recon Vehicles",
          vehicles: 181,
          avgHours: 72.2,
          maxHours: 140.4,
          targetHours: 48,
          blockers: 9,
          assignedTeam: "Inventory Intake",
          utilization: 94,
          status: "watch",
          trend: "up",
        },
      ],
    },
    {
      code: "inspection-estimating",
      label: "Approval & Review",
      totalVehicles: 86,
      avgCycleDays: 2.8,
      rows: [
        {
          code: "check-in-open-ro",
          label: "RO Open",
          vehicles: 26,
          avgHours: 3.2,
          maxHours: 9.1,
          targetHours: 2,
          blockers: 1,
          assignedTeam: "Service Advisors",
          utilization: 72,
          status: "watch",
          trend: "flat",
        },
        {
          code: "approval-pending",
          label: "Approval pending",
          vehicles: 9,
          avgHours: 3.0,
          maxHours: 12.4,
          targetHours: 1,
          blockers: 2,
          assignedTeam: "UCM Approval Desk",
          utilization: 88,
          status: "blocked",
          trend: "up",
        },
        {
          code: "finalize-approval",
          label: "Finalize approval",
          vehicles: 3,
          avgHours: 1.5,
          maxHours: 4.2,
          targetHours: 1,
          blockers: 0,
          assignedTeam: "Manager Desk",
          utilization: 50,
          status: "healthy",
          trend: "flat",
        },
      ],
    },
    {
      code: "approved-work",
      label: "Approved Work In Process",
      totalVehicles: 28,
      avgCycleDays: 1.6,
      rows: [
        {
          code: "parts-fulfillment",
          label: "Parts Fulfillment",
          vehicles: 9,
          avgHours: 2.0,
          maxHours: 11.4,
          targetHours: 2,
          blockers: 2,
          assignedTeam: "Parts Back Counter",
          utilization: 77,
          status: "watch",
          trend: "up",
        },
        {
          code: "offsite-warranty",
          label: "Offsite for Warranty/Recall",
          vehicles: 2,
          avgHours: 0.0,
          maxHours: 18.0,
          targetHours: 12,
          blockers: 0,
          assignedTeam: "Vendor Coordination",
          utilization: 25,
          status: "healthy",
          trend: "flat",
        },
        {
          code: "mechanical-repairs",
          label: "Mechanical Repairs",
          vehicles: 5,
          avgHours: 2.7,
          maxHours: 14.1,
          targetHours: 3,
          blockers: 1,
          assignedTeam: "Shop Floor",
          utilization: 84,
          status: "healthy",
          trend: "down",
        },
        {
          code: "close-ro",
          label: "Close RO",
          vehicles: 1,
          avgHours: 0.1,
          maxHours: 1.2,
          targetHours: 0.5,
          blockers: 0,
          assignedTeam: "Service Cashier",
          utilization: 31,
          status: "healthy",
          trend: "flat",
        },
        {
          code: "body-shop",
          label: "Body Shop",
          vehicles: 2,
          avgHours: 0.0,
          maxHours: 24.0,
          targetHours: 16,
          blockers: 0,
          assignedTeam: "Collision Vendor",
          utilization: 52,
          status: "healthy",
          trend: "flat",
        },
        {
          code: "detail",
          label: "Detail",
          vehicles: 8,
          avgHours: 0.0,
          maxHours: 4.5,
          targetHours: 2,
          blockers: 1,
          assignedTeam: "Detail Ops",
          utilization: 95,
          status: "watch",
          trend: "up",
        },
      ],
    },
    {
      code: "merchandising",
      label: "Merchandising & Ready Line",
      totalVehicles: 19,
      avgCycleDays: 0.9,
      rows: [
        {
          code: "photo",
          label: "Photography",
          vehicles: 6,
          avgHours: 1.6,
          maxHours: 6.4,
          targetHours: 2,
          blockers: 0,
          assignedTeam: "Media Bay",
          utilization: 74,
          status: "healthy",
          trend: "down",
        },
        {
          code: "pricing",
          label: "Pricing",
          vehicles: 7,
          avgHours: 4.2,
          maxHours: 8.8,
          targetHours: 3,
          blockers: 1,
          assignedTeam: "Merchandising Desk",
          utilization: 81,
          status: "watch",
          trend: "up",
        },
        {
          code: "ready-for-sale",
          label: "Ready For Sale",
          vehicles: 6,
          avgHours: 0.8,
          maxHours: 1.5,
          targetHours: 1,
          blockers: 0,
          assignedTeam: "Inventory Release",
          utilization: 58,
          status: "healthy",
          trend: "flat",
        },
      ],
    },
  ],
  alerts: [
    {
      code: "approval-backlog",
      title: "Approval backlog building",
      detail: "9 units have crossed the 1 hour approval target. UCM desk is the current choke point.",
      severity: "critical",
    },
    {
      code: "inspection-load",
      title: "Inspection lane over capacity",
      detail: "Mechanical inspection is at 91% utilization with 3 vehicles carrying blockers.",
      severity: "watch",
    },
    {
      code: "pricing-flow",
      title: "Merchandising catch-up underway",
      detail: "Photography is trending down, but pricing is starting to stack after noon intake.",
      severity: "info",
    },
  ],
  staffLoad: [
    {
      team: "Inspection",
      activeUnits: 27,
      capacity: 30,
      status: "critical",
    },
    {
      team: "Parts",
      activeUnits: 23,
      capacity: 32,
      status: "watch",
    },
    {
      team: "Mechanical",
      activeUnits: 18,
      capacity: 24,
      status: "healthy",
    },
    {
      team: "Detail",
      activeUnits: 8,
      capacity: 8,
      status: "watch",
    },
    {
      team: "Merch",
      activeUnits: 13,
      capacity: 20,
      status: "healthy",
    },
  ],
};
